name: PHP Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: PHP Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: PHP Lint
        run: php -l src/

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-scripts --no-progress --no-suggest

      - name: Run PHPStan
        run: composer analyze

  cs-fixer:
    name: PHP CS Fixer
    runs-on: ubuntu-latest
    needs: phpstan
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-scripts --no-progress --no-suggest

      - name: Run PHP CS Fixer
        run: vendor/bin/php-cs-fixer fix --dry-run --diff src

  rector:
    name: Rector
    runs-on: ubuntu-latest
    needs: phpstan
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-scripts --no-progress --no-suggest

      - name: Run rector
        run: vendor/bin/rector --dry-run

  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    needs: phpstan
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-scripts --no-progress --no-suggest

      - name: Run PHPUnit
        env:
          XDEBUG_MODE: coverage
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml
          fail_ci_if_error: true